version: '3.8'

networks:
  kustdesk-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

services:
  # KustDesk Server (ID + Relay)
  kustdesk-server:
    image: kayung1012/kustdesk-server:latest  # 使用你的镜像
    container_name: kustdesk-server
    environment:
      - RELAY=192.168.1.66:8017
      - ENCRYPTED_ONLY=1
      - TZ=Asia/Shanghai
      - RUSTDESK_API_RUSTDESK_ID_SERVER=192.168.1.66:8016
      - RUSTDESK_API_RUSTDESK_RELAY_SERVER=192.168.1.66:8017
      - RUSTDESK_API_RUSTDESK_API_SERVER=http://192.168.1.66:8014
    ports:
      - "8015:21115"      # TCP hole punching (映射到8015)
      - "8016:21116"      # ID server (映射到8016)
      - "8016:21116/udp"  # ID server UDP (映射到8016)
      - "8017:21117"      # Relay server (映射到8017)
      - "8018:21118"      # Web client (映射到8018)
      - "8019:21119"      # Web client HTTPS (映射到8019)
    volumes:
      - ./data/rustdesk/server:/data
      - ./data/rustdesk/api:/app/data
    networks:
      - kustdesk-net
    restart: unless-stopped

  # KustDesk API (包含API + Web)
  kustdesk-api:
    image: kayung1012/kustdesk-api:latest
    container_name: kustdesk-api
    environment:
      - TZ=Asia/Shanghai
      - RUSTDESK_API_LANG=zh-CN
      - RUSTDESK_API_RUSTDESK_ID_SERVER=192.168.1.66:8016
      - RUSTDESK_API_RUSTDESK_RELAY_SERVER=192.168.1.66:8017
      - RUSTDESK_API_RUSTDESK_API_SERVER=http://192.168.1.66:8014
      - RUSTDESK_API_RUSTDESK_KEY=your_rustdesk_key_here
      - RUSTDESK_API_APP_WEB_CLIENT=1
      - RUSTDESK_API_APP_REGISTER=false
      - RUSTDESK_API_APP_SHOW_SWAGGER=0
      - RUSTDESK_API_APP_MAX_CONCURRENT_DEVICES=3
    ports:
      - "8014:21114"      # API服务 (映射到8014)
    volumes:
      - ./data/rustdesk/api:/app/data
      - ./conf:/app/conf
      - ./logs:/app/runtime
    networks:
      - kustdesk-net
    restart: unless-stopped
    depends_on:
      - kustdesk-server

volumes:
  kustdesk-server-data:
    driver: local
  kustdesk-api-data:
    driver: local
